cart/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', login_required(views.CartView.as_view(), login_url='user:register'), name='cart'),
    path('add/<int:pk>/', views.add_to_cart, name='add'),
    path('update/', views.update_all_objects, name='update_all'),
    path('delete/<int:pk>/', views.delete_from_cart, name='delete'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('checkout/', login_required(views.CheckoutView.as_view(), login_url='user:register'), name='checkout'),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.MenuView.as_view(), name='menu'),
    path('detail/<int:pk>/', views.FoodDetailView.as_view(), name='detail'),
]

orders/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', login_required(views.OrdersView.as_view(), login_url='user:register'), name='orders'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('about/', views.about, name='about'),

    path('menu/', include(('menu.urls', 'menu'))),
    path('cart/', include(('cart.urls', 'cart'))),
    path('orders/', include(('orders.urls', 'orders'))),
    path('user/', include(('user.urls', 'user'))),
]

cart/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.conf import settings

from menu.models import Food


class CartManager(models.Manager):
    def limit_check(self, user, amount_to_add=None, input_amounts=None):
        qs = super().get_queryset().filter(user=user)

        limit_number = 50
        cart_amounts = [int(i.amount) for i in qs]

        if amount_to_add:
            if amount_to_add + sum(cart_amounts) > limit_number:
                raise ValueError(f"Amount value can not overcome cart's limit of {limit_number}.")
        if input_amounts:
            if sum(input_amounts) + sum(cart_amounts) - sum(cart_amounts) > limit_number:
                raise ValueError(f"Total amount value can not overcome cart's limit of {limit_number}.")

    def stock_check(self, user, menu_object, amount_to_add):
        qs = super().get_queryset().filter(menu__name=menu_object.name, user=user)

        if qs.exists():
            qs_object = super().get_queryset().get(menu__name=menu_object.name, user=user)
            menu_object_amount = qs_object.amount
        else:
            menu_object_amount = 0

        if amount_to_add + menu_object_amount > menu_object.stock:
            raise ValueError(f"Amount value can not be greater than {menu_object.name}'s stock value.")


class Cart(models.Model):
    menu = models.ForeignKey(Food, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=100, decimal_places=2)
    amount = models.PositiveIntegerField(default=1, validators=[
        MinValueValidator(1, message='Amount can not be less than 1')])
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    objects = CartManager()

    def __str__(self):
        return self.menu.name

    class Meta:
        ordering = ['menu__name']


class Payment(models.Model):
    payment = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.payment

cart/forms.py
from django import forms
from .models import Cart, Payment


class AmountForm(forms.ModelForm):
    amount = forms.IntegerField(widget=forms.NumberInput(attrs={
        'required': 'False',
    }), required=False)

    class Meta:
        model = Cart
        fields = ['amount']


class CheckoutForm(forms.ModelForm):
    email = forms.EmailField(required=False)
    payment_type = forms.ModelChoiceField(widget=forms.Select(attrs={
        'required': 'True',
    }), empty_label=None, queryset=Payment.objects.all())

    class Meta:
        model = Payment
        fields = ['email', 'payment_type']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""  # Removes : as label suffix

        self.fields['email'].label = 'Email address'
        self.fields['payment_type'].label = 'Payment type'
        self.fields['email'].help_text = 'Leave blank for default'

cart/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.generic import View
from django.core.paginator import Paginator

from menu.models import Food
from orders.models import Order
from .models import Cart
from .forms import AmountForm, CheckoutForm


class CartView(View):
    def get(self, *args, **kwargs):
        cart = Cart.objects.select_related('menu').filter(user=self.request.user)
        form = AmountForm()

        if cart.count() == 0:
            total_price = 0
            total_amount = 0
        else:
            total_price = float(cart.aggregate(Sum('price'))['price__sum'])
            total_amount = cart.aggregate(Sum('amount'))['amount__sum']

        paginator = Paginator(cart, 10)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'page_obj': page_obj,
            'total_price': total_price,
            'form': form,
        }

        self.request.session['cart_total'] = total_amount
        return render(self.request, 'cart/cart.html', context)


@login_required(login_url='user:register')
def add_to_cart(request, pk):
    """Adds or creates object of Menu to Cart with typed-in amount."""
    if request.method == 'POST':
        menu_object = get_object_or_404(Food, pk=pk)
        amount_to_add = int(request.POST.get('amount', 1))
        form = AmountForm(request.POST)
        if form.is_valid():
            try:
                Cart.objects.limit_check(amount_to_add=amount_to_add, user=request.user)
                Cart.objects.stock_check(menu_object=menu_object, amount_to_add=amount_to_add, user=request.user)
                if Cart.objects.filter(menu__name=menu_object.name, user=request.user).exists():
                    cart_object = get_object_or_404(Cart, menu__name=menu_object.name, user=request.user)
                    cart_object.price += (cart_object.price / cart_object.amount) * amount_to_add
                    cart_object.amount += amount_to_add
                    cart_object.save()
                else:
                    Cart.objects.create(
                        menu=menu_object,
                        price=menu_object.price * amount_to_add,
                        user=request.user,
                        amount=amount_to_add,
                    )

                cart_total = Cart.objects.filter(user=request.user).aggregate(Sum('amount'))['amount__sum']
                request.session['cart_total'] = cart_total
                messages.success(request, f'{menu_object.name} ({amount_to_add}) has been added to cart')

            except ValueError as error_message:
                messages.error(request, error_message)

        messages.error(request, form.errors)
        return redirect(request.META.get('HTTP_REFERER'))  # redirect to the same page


@login_required(login_url='user:register')
def update_all_objects(request):
    """Updates amounts and prices for EVERY object in cart."""
    if request.method == 'POST':
        form = AmountForm(request.POST)
        if form.is_valid():
            input_amounts = [int(i) for i in request.POST.getlist('amount', None)]
            x = 0
            try:
                Cart.objects.limit_check(input_amounts=input_amounts, user=request.user)
                for input_number in input_amounts:
                    cart_object_name = Cart.objects.filter(user=request.user)[x]
                    cart_object = get_object_or_404(Cart, menu__name=cart_object_name, user=request.user)
                    if input_number <= cart_object.menu.stock and input_number != cart_object.amount:
                        cart_object.price = cart_object.price / cart_object.amount * input_number
                        cart_object.amount = input_number
                        cart_object.save()
                    x += 1
                messages.success(request, 'Cart has been updated')

            except ValueError as error_message:
                messages.error(request, error_message)

        messages.error(request, form.errors)
        return redirect('cart:cart')


@login_required(login_url='user:register')
def delete_from_cart(request, pk):
    if request.method == 'POST':
        cart_object = Cart.objects.select_related('menu').get(pk=pk, user=request.user)
        cart_object.delete()

        messages.success(request, f'{cart_object.menu.name} successfully deleted')
        return redirect('cart:cart')


@login_required(login_url='user:register')
def clear_cart(request):
    if request.method == 'POST':
        cart = Cart.objects.filter(user=request.user)
        cart.delete()

        messages.success(request, 'Cart successfully cleared')
        return redirect('cart:cart')


class CheckoutView(View):
    def get(self, *args, **kwargs):
        cart = Cart.objects.select_related('menu').filter(user=self.request.user)
        total_price = float(cart.aggregate(Sum('price'))['price__sum'])
        form = CheckoutForm()
        context = {
            'cart': cart,
            'total_price': total_price,
            'form': form,
        }
        return render(self.request, 'cart/checkout.html', context)

    def post(self, *args, **kwargs):
        """
        1. Gets all data for Order table.
        2. Creates Order table.
        3. Decreases stock value of menu objects and clears cart.
        """
        cart = Cart.objects.select_related('menu').filter(user=self.request.user)

        form = CheckoutForm(self.request.POST)
        if form.is_valid():
            # 1
            products = {}
            for cart_object in cart:
                object_info = {
                    cart_object.menu.name: {
                        'image': cart_object.menu.image.url,
                        'amount': cart_object.amount,
                        'price': float(cart_object.price),
                    }
                }
                products.update(object_info)
            if form.cleaned_data['email'] == '':
                email_address = self.request.user.email
            else:
                email_address = form.cleaned_data['email']
            payment_type = form.cleaned_data['payment_type']
            total_amount = cart.aggregate(Sum('amount'))['amount__sum']
            total_price = cart.aggregate(Sum('price'))['price__sum']

            # 2
            Order.objects.create(
                products=products,
                email_address=email_address,
                payment_type=payment_type,
                total_amount=total_amount,
                total_price=total_price,
                user=self.request.user,
            )

            # 3
            for cart_object in cart:
                cart_object.menu.stock -= cart_object.amount
                cart_object.menu.save()
            cart.delete()

            context = {
                'email_address': email_address,
            }

            self.request.session['cart_total'] = 0
            messages.success(self.request, 'Successfull purchase!')
            return render(self.request, 'cart/checkout_success.html', context)

cart/templates/cart/cart.html
{% extends 'base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}

<div id="banner">
  <div class="banner_image banner_image_cart"></div>
  <h1 class="text-center banner_text text-white user-select-none">Cart</h1>
</div>
<div class="container mt-5">
  {% if page_obj.paginator.count != 0 %}
  <div class="justify-content-between mt-4">
    <div class="d-flex">
      <h2 class="text-primary">Your cart: <span class="badge cart_badge">{{ request.session.cart_total }}/50 in total</span></h2>
      <!-- Button trigger modal clear cart -->
      <a href='#' class="btn btn-cart_delete btn-lg btn-outline-dark" data-bs-toggle="modal" data-bs-target="#modal-clear-cart">
        <i class="fa-solid fa-trash"></i>
      </a>
      <!-- Modal Clear Cart -->
      <div class="modal fade" id="modal-clear-cart" tabindex="-1" aria-labelledby="DeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="ClearCartModalLabel">Confirmation</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to delete all objects in cart?</p>
            </div>
            <div class="modal-footer">
              <form method="POST" action="{% url 'cart:clear_cart' %}"> {% csrf_token %}
                <button class="btn btn-outline-primary me-2" type="submit">Confirm</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- ############ -->
    </div>
  </div>
  <form method="POST" action="{% url 'cart:update_all' %}"> {% csrf_token %}
    <table class="table table-borderless">
      <tbody>
        {% for cart_object in page_obj %}
        <tr>
          <td class="align-middle cart_object_table_image">
            <a href="{% url 'menu:detail' cart_object.menu.pk %}" class="text-decoration-none link-secondary">
              <img src="{{ cart_object.menu.image.url }}" class="cart_object_image">
            </a>
          </td>
          <td class="align-middle cart_object_table_name">
            <a href="{% url 'menu:detail' cart_object.menu.pk %}" class="text-decoration-none link-secondary">
              <h5>{{ cart_object.menu.name }}</h5>
            </a>
          </td>
          <td class="align-middle">
            <input type="submit" id="submit-form" style="visibility: hidden;">
          </td>
          <td class="align-middle">
            <h5>${{ cart_object.price }}</h5>
          </td>
          <td class="align-middle">
            <input type="number" min="1" max="50" oninput="this.value = Math.abs(this.value)" name="amount" id="amount_{{ forloop.counter }}" class="form-control form_control_amount" value="{{ cart_object.amount }}">
          </td>
          <td class="align-middle">
            <h5>{% if cart_object.menu.stock == 0 %} OUT OF STOCK {% else %}{{ cart_object.menu.stock }} left {% endif %}</h5>
          </td>
          <td class="align-middle">
            <!-- Button trigger modal delete -->
            <a href='#' class="text-decoration-none" data-bs-toggle="modal" data-bs-target="#modal-delete-item-{{ cart_object.pk }}">
              <h5><i class="fa-solid fa-xmark text-danger"></i></h5>
            </a>
            <!-- Modal delete -->
            <div class="modal fade" id="modal-delete-item-{{ cart_object.pk }}" tabindex="-1" aria-labelledby="DeleteModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="DeleteModalLabel">Confirmation</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <p>Are you sure you want to delete "{{ cart_object.menu.name }}"?</p>
                  </div>
                  <div class="modal-footer">
                    <!-- this form IS NOT visible (IDK WHY) -->
                    <form>
                    </form>
                    <form method="POST" action="{% url 'cart:delete' cart_object.pk %}"> {% csrf_token %}
                      <button class="btn btn-outline-primary me-2" type="submit">Confirm</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <!-- ############ -->
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </form>
  {% endif %}

  {% if page_obj.paginator.num_pages > 1 %}
  <!-- Pagination -->
  <nav aria-label="Page navigation example page_navigation">
    <ul class="pagination justify-content-center mt-5">
      <li class="page-item {% if page_obj.has_previous %}enabled{% else %}disabled{% endif %}">
        <a class="page-link" href="?page=1" aria-label="First">
          <span aria-hidden='true'>&laquo;</span>
        </a>
      </li>
      {% for page in page_obj.paginator.page_range %}
      <li class="page-item {% if page == page_obj.number %} active {% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
      {% endfor %}
      <li class="page-item {% if page_obj.has_next %}enabled{% else %}disabled{% endif %}">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
  {% endif %}

  {% if page_obj.paginator.count == 0 %}
  <div class="text-center">
    <h1>Your cart is currently empty</h1>
    <a type="button" class="btn btn-lg btn-outline-dark btn_back_to_cart" href="{% url 'menu:menu' %}">Order Now</a>
  </div>
  {% else %}
  <div class="d-flex flex-row justify-content-between flex-wrap mt-4">
    <div class="back_to_menu_col">
      <a type="button" class="btn btn-lg btn-outline-dark btn_back_to_cart" href="{% url 'menu:menu' %}"><i class="fa-solid fa-arrow-left"></i> Back to ordering</a>
    </div>
    <div class="p-2 me-2">
      <h4 class="text-end">Total (USD): ${{ total_price }}</h4>
    </div>
    <div class="me-2">
      <button class="btn btn-lg btn-outline-success" onclick="document.getElementById('submit-form').click()">Save</button>
    </div>
    <div class="">
      <a type="button" href="{% url 'cart:checkout' %}" class="btn btn-lg btn-primary">Proceed to Checkout</a>
    </div>
  </div>
  {% endif %}

</div>
{% endblock %}

cart/templates/cart/checkout.html
{% extends 'base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}

{% load widget_tweaks %}

<div class="container user_form d-flex justify-content-center">
  <div class="row g-5 w-50">
    <div class="col order-md-last">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-primary">Your cart</span>
        <span class="badge bg-primary rounded-pill">{{ request.session.cart_total }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for cart_object in cart %}
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0">{{ cart_object.menu.name }}</h6>
            <small class="text-muted">x{{ cart_object.amount }}</small>
          </div>
          <span class="text-muted">${{ cart_object.price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>${{ total_price }}</strong>
        </li>
      </ul>

    </div>
    <div class="col">
      <h3 class="mb-3">Payment info</h3>
      <form method="POST"> {% csrf_token %}
        <div class="col-sm-13">
          {% for field in form %}
          <div class="mb-3">
            <label class="form-label">{{ field.label }}</label>
            {% render_field field class="form-control" placeholder=field.help_text %}
          </div>
          {% endfor %}
        </div>
        <hr class="my-4">
        <button class="w-100 btn btn-primary btn-lg" type="submit">Finish payment</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

cart/templates/cart/checkout_success.html
{% extends 'base.html' %}

{% block title %}Successful payment{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center mt-5">
  <div class="w-25 text-center">
    <h1 class="mb-2">Thank you!</h1>
    <p class="text-secondary">You can look at your purchases in the orders or proceed on browsing the Menu</p>
    <div class="d-flex text-center justify-content-center mt-2">
      <a type="button" class="btn btn-lg btn-outline-dark" href="{% url 'menu:menu' %}">Back to Menu</a>
      <a type='button' class="btn btn-lg btn-primary ms-3" href="{% url 'orders:orders' %}">Orders</a>
    </div>
  </div>
</div>
{% endblock %}