cart/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', login_required(views.CartView.as_view(), login_url='user:register'), name='cart'),
    path('add/<int:pk>/', views.add_to_cart, name='add'),
    path('update/', views.update_all_objects, name='update_all'),
    path('delete/<int:pk>/', views.delete_from_cart, name='delete'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('checkout/', login_required(views.CheckoutView.as_view(), login_url='user:register'), name='checkout'),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.MenuView.as_view(), name='menu'),
    path('detail/<int:pk>/', views.FoodDetailView.as_view(), name='detail'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('about/', views.about, name='about'),

    path('menu/', include(('menu.urls', 'menu'))),
    path('cart/', include(('cart.urls', 'cart'))),
    path('orders/', include(('orders.urls', 'orders'))),
    path('user/', include(('user.urls', 'user'))),
]

menu/models.py
from django.db import models
from django.core.validators import MinValueValidator


class Category(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Food(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(upload_to='static/menu/images/')
    price = models.DecimalField(max_digits=100, decimal_places=2)
    stock = models.PositiveIntegerField(default=1, validators=[MinValueValidator(0)])
    categories = models.ManyToManyField(Category, blank=True)

    def __str__(self):
        return f"{self.name} ({self.stock})"

    class Meta:
        ordering = ['name']

    def update_cart_object_values(self):
        from cart.models import Cart

        qs = Cart.objects.filter(menu__name=self.name)
        if self.stock == 0:
            qs.delete()
        else:
            for cart_object in qs:
                if self.stock < cart_object.amount:
                    cart_object.amount = cart_object.amount - (cart_object.amount - self.stock)
                cart_object.price = self.price * cart_object.amount
                cart_object.save()

    def save(self, *args, **kwargs):
        self.update_cart_object_values()
        super().save(*args, **kwargs)

menu/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import ModelFormMixin

from .models import Food
from cart.forms import AmountForm


class MenuView(ListView):
    queryset = Food.objects.prefetch_related("categories").all()
    context_object_name = 'foods'
    paginate_by = 8
    template_name = "menu/menu.html"


class FoodDetailView(DetailView, ModelFormMixin):
    model = Food
    form_class = AmountForm
    template_name = "menu/food_detail.html"


# def food_detail(request, pk):
#     food_object = get_object_or_404(Food, pk=pk)
#     form = AmountForm
#
#     context = {
#         'food': food_object,
#         'form': form,
#     }
#
#     return render(request, 'menu/food_detail.html', context)

menu/templates/menu/food_detail.html
{% extends 'base.html' %}

{% block title %}{{ food.name }}{% endblock %}

{% load static %}

{% block content %}

{% load widget_tweaks %}

<div class="container mt-5">
  <div class="food_detail d-flex flex-wrap justify-content-center">
    <img class="food_detail_image" src="{{ food.image.url }}">
    <div class='food_detail_info ms-5'>
      <h1>{{ food.name }}</h1>
      <div class="mb-4 mt-4">
        <h2>${{ food.price }} <span class="badge cart_badge ms-3">{{ food.stock }} left</span></h2>
      </div>
      <hr>
      <p class="">{{ food.description }}</p>
      <hr>

      {% if food.stock == 0 %}
      <button type="submit" class="btn btn-lg btn-outline-dark" disabled>OUT OF STOCK</button>
      {% else %}

      <form method="POST" action="{% url 'cart:add' food.pk %}"> {% csrf_token %}
        <div class="d-flex mt-4">
          {% for field in form %}
          {% render_field field name="amount" min="1" max="50" oninput="this.value = Math.abs(this.value)" class="form-control form_control_amount_detail" value="1" %}
          {% endfor %}
          <div class="ms-3">
            <button type="submit" class="btn btn-lg btn-outline-dark">Add to Cart</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

menu/templates/menu/menu.html
{% extends 'base.html' %}

{% block title %}Menu{% endblock %}

{% load static %}

{% block content %}
<div class="bg-white">
  <div id="banner">
    <div class="banner_image banner_image_menu"></div>
    <h1 class="text-center banner_text text-white user-select-none">Menu</h1>
  </div>
  <div class="container mt-5">
    <div class="row row-cols-xxl-4 row-cols-xl-4 row-cols-lg-3 row-cols-md-2 row-cols-sm-2 g-4">
      {% for food in foods %}
      <div class="col">
        <div class="card bg-transparent">
          <a href="{% url 'menu:detail' food.pk %}" class="card_image_link text-decoration-none">
            <img src="{{ food.image.url }}" class="card-img-top card_image">
          </a>
          <div class="card-body">
            <a href="{% url 'menu:detail' food.pk %}" class="card_text_link link-dark text-decoration-none">
              <h3 class="card-title card_title_text">{{ food.name }}</h3>
            </a>
            <h6 class="text-muted">
              {% for category in food.categories.all|slice:":5" %}
              {% if forloop.counter != 5 %}
              {{ category }} /
              {% else %}
              ...
              {% endif %}
              {% endfor %}
            </h6>
          </div>
          <div class="card-footer bg-transparent">
            <h5 class="card_footer_element">${{ food.price }}</h5>
            {% if food.stock == 0 %}
            <button type="submit" class="btn btn-outline-dark btn_add_to_cart" disabled>OUT OF STOCK</button>
            {% else %}
            <form method="POST" action="{% url 'cart:add' food.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-dark btn_add_to_cart">Add to Cart</button>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  {% if page_obj.paginator.num_pages > 1 %}
  <!-- Pagination -->
  <nav aria-label="Page navigation example page_navigation">
    <ul class="pagination justify-content-center mt-5">
      <li class="page-item {% if page_obj.has_previous %}enabled{% else %}disabled{% endif %}">
        <a class="page-link" href="?page=1" aria-label="First">
          <span aria-hidden='true'>&laquo;</span>
        </a>
      </li>
      {% for page in page_obj.paginator.page_range %}
      <li class="page-item {% if page == page_obj.number %} active {% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
      {% endfor %}
      <li class="page-item {% if page_obj.has_next %}enabled{% else %}disabled{% endif %}">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
  {% endif %}

</div>
{% endblock %}