cart/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', login_required(views.CartView.as_view(), login_url='user:register'), name='cart'),
    path('add/<int:pk>/', views.add_to_cart, name='add'),
    path('update/', views.update_all_objects, name='update_all'),
    path('delete/<int:pk>/', views.delete_from_cart, name='delete'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('checkout/', login_required(views.CheckoutView.as_view(), login_url='user:register'), name='checkout'),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.MenuView.as_view(), name='menu'),
    path('detail/<int:pk>/', views.FoodDetailView.as_view(), name='detail'),
]

orders/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', login_required(views.OrdersView.as_view(), login_url='user:register'), name='orders'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('about/', views.about, name='about'),

    path('menu/', include(('menu.urls', 'menu'))),
    path('cart/', include(('cart.urls', 'cart'))),
    path('orders/', include(('orders.urls', 'orders'))),
    path('user/', include(('user.urls', 'user'))),
]

user/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'user'

urlpatterns = [
    path('register', views.RegisterUserView.as_view(), name='register'),
    path('log-in', views.LoginUserView.as_view(), name='login'),
    path('log-out', login_required(views.LogoutUserView.as_view(), login_url='user:register'), name='logout'),
]

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}

<div id="banner">
  <div class="banner_image banner_image_about"></div>
  <h1 class="text-center banner_text text-white user-select-none">About</h1>
</div>
<div class="container mt-5">
  <div class="text-center">
    <div class="mb-5">
      <h1>Hello</h1>
      <h5>Thank you for using my site</h5>
      <h5>This site was made by me for educational cause</h5>
    </div>
    <div>
      <h1>Links</h1>
      <a href="https://github.com/Sobikaa-droid" class="link-primary text-decoration-none">
        <h5>My GitHub page</h5>
      </a>
      <a href="https://github.com/Sobikaa-droid/django-restaurant" class="link-primary text-decoration-none">
        <h5>Website source code</h5>
      </a>
    </div>
  </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %} | Le Petite Appétit</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'custom.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@500&family=Corinthia&family=Indie+Flower&family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
  <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-white sticky-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}"><img class='navbar_logo' src="{% static 'restaurant_logo_pink.png' %}" width="50" height="50"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item ms-2">
            <a class="nav-link {% if request.path == '/menu/' %} active {% endif %}" aria-current="page" href="{% url 'menu:menu' %}">Menu</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item ms-2">
            <a class="nav-link {% if request.path == '/orders/' %} active {% endif %}" href="{% url 'orders:orders' %}" aria-current="page">Orders</a>
          </li>
          {% endif %}
          <li class="nav-item ms-2">
            <a class="nav-link {% if request.path == '/about/' %} active {% endif %}" aria-current="page" href="{% url 'about' %}">About</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-toggle="dropdown">
              {{ user.username }}
            </a>
            <ul class="dropdown-menu site-menu">
              <li>
                <a class="nav-link" href="{% url 'user:logout' %}" aria-current="page" type='submit'><i class="fa-solid fa-right-from-bracket"></i> Log Out</a>
              </li>
            </ul>
          </li>

          {% else %}
          <li class="nav-item ms-2">
            <a class="nav-link {% if request.path == '/user/register' %} active {% endif %}" aria-current="page" href="{% url 'user:register' %}">Sign Up</a>
          </li>
          <li class="nav-item ms-2">
            <a class="nav-link {% if request.path == '/user/login' %} active {% endif %}" aria-current="page" href="{% url 'user:login' %}">Log In</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item ms-2">
            <a class="nav-link {% if request.path == '/cart/' %} active {% endif %}" aria-current="page" href="{% url 'cart:cart' %}">
              <i class="fa-solid fa-basket-shopping"></i>
              <span class="badge rounded-pill">{{ request.session.cart_total }} {% if request.session.cart_total == 50 %} (MAX) {% endif %}</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}
  {% endblock %}

  <footer class="container">
    <hr class="mt-5 border border-1 opacity-75 footer_hr">
    <div class="text-center footer_div">
      <!--        <h4><a href="https://github.com/Sobikaa-droid" class="link-secondary"><i class="fa-brands fa-github"></i></a></h4>-->
      <p class="footer_p">© Le Petite Appétit {% now "Y" %} ®</p>
    </div>
  </footer>

  <!-- MESSAGE -->
  {% if messages %}
  {% for message in messages %}
  <div role="alert" aria-live="assertive" aria-atomic="true" class="toast show me-4 mb-4" data-bs-autohide="true" style="position: fixed; bottom: 0; right: 0;">
    <div class="toast-header">
      <i class="fa-solid fa-circle {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} text-danger {% else %} text-success {% endif %} me-2"></i>
      <strong class="me-auto">{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} Error {% else %} Success {% endif %}</strong>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
      {{ message }}
    </div>
  </div>
  {% endfor %}
  {% endif %}

  <!--  &lt;!&ndash; MESSAGE OLD &ndash;&gt;-->
  <!--  {% if messages %}-->
  <!--  {% for message in messages %}-->
  <!--  <div class="toast align-items-center border-0 show me-4 mb-4" role="alert" aria-live="assertive" aria-atomic="true" style="position: fixed; bottom: 0; right: 0;">-->
  <!--    <div class="d-flex">-->
  <!--      <div class="toast-body">-->
  <!--        {{ message }}-->
  <!--      </div>-->
  <!--      <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>-->
  <!--    </div>-->
  <!--  </div>-->
  <!--  {% endfor %}-->
  <!--  {% endif %}-->

  <script src="https://kit.fontawesome.com/40bf0cc06c.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Cartoon Restaurant{% endblock %}

{% block content %}

{% load static %}

<div id="banner">
  <div class="banner_image banner_image_home"></div>
  <h1 class="text-center banner_text banner_home_text text-white user-select-none">Le Petite Appétit</h1>
</div>
<div class="container">
  <div class="px-4 my-5 text-center">
    <img class='navbar_logo mb-3' src="{% static 'bart-simpson.gif' %}" width="130" height="100">
    <h1 class="display-6 fw-bold">Welcome</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-3 text-secondary">Curabitur non faucibus neque. Nulla ac mauris luctus, pellentesque sem at, efficitur purus. In nunc dui, ornare viverra lectus ut, ornare pulvinar velit. Maecenas facilisis risus sit amet tincidunt posuere. Nunc dignissim ex eu auctor feugiat.</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a type="button" href="{% url 'menu:menu' %}" class="btn btn-lg btn-outline-dark btn-lg px-4 gap-3">Browse the Menu</a>
      </div>
    </div>
  </div>
  <hr class="border border-1 opacity-75 footer_hr">
  <div class="container py-5" id="hanging-icons">
    <div class="row g-4 mt-5 mb-4 row-cols-1 row-cols-lg-3">
      <div class="col d-flex align-items-start">
        <div class="icon-square d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
          <h2 class="icon_pink"><i class="fa-solid fa-truck-fast"></i></h2>
        </div>
        <div>
          <h3 class="fs-2">Fast delivery</h3>
          <p class="text-secondary">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vitae turpis faucibus, auctor elit ut, feugiat velit. Quisque neque tortor, mattis ut lobortis id, tristique ut ante.</p>
        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div class="icon-square d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
          <h2 class="icon_pink"><i class="fa-solid fa-gem"></i></h2>
        </div>
        <div>
          <h3 class="fs-2">Quality</h3>
          <p class="text-secondary">Vestibulum gravida velit augue, vitae commodo nisl faucibus eu. Pellentesque tincidunt ultricies justo. Cras feugiat arcu a massa pellentesque, eget blandit metus auctor.</p>
        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div class="icon-square d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
          <h2 class="icon_pink"><i class="fa-solid fa-tags"></i></h2>
        </div>
        <div>
          <h3 class="fs-2">Hot prices</h3>
          <p class="text-secondary">Pellentesque tincidunt ultricies justo. Cras feugiat arcu a massa pellentesque, eget blandit metus auctor. In eget turpis euismod, hendrerit est at, consectetur lectus.</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}